name: hourly-cron
on:
  schedule:
    - cron: "* * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
      - shell: bash
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          curl --request POST \
          --url 'https://line-web-serverless-857x.vercel.app/api/cron' \
          --header "Authorization: Bearer "$env.CRON_SECRET"" \
          -w '\n Response code: %{http_code}\n'
