name: hourly-cron
on:
  schedule:
    - cron: "* * * * *"
env:
  SOME_SECRET: ${{ secrets.CRON_SECRET }}
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://line-web-serverless-857x.vercel.app/api/cron' \
          --header "Authorization: Bearer ${{ env.CRON_SECRET }}"
